### ISSUE TITLE
Rename this repo to maquiavelo

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/Maquiavelo#1]
Rename this repo to `maquiavelo`?
Note the lower-case `m`.

**Comment by David-Estevez** [comment]
This is a conscious decision:

* https://github.com/foosel/OctoPrint
* https://github.com/FreeCAD/FreeCAD-library
* https://github.com/Lauszus/Sanguino
* https://github.com/MarlinFirmware/Marlin

**Comment by jgvictores** [comment]
Kind of breaks with the de-facto of the rest of https://github.com/asrob-uc3m :-(

**Comment by David-Estevez** [comment]
* https://github.com/asrob-uc3m/HackLab
* https://github.com/asrob-uc3m/LedStripControl
* https://github.com/asrob-uc3m/MYOD
* https://github.com/asrob-uc3m/ASROB-sumo
* https://github.com/asrob-uc3m/ASROB-racing
* https://github.com/asrob-uc3m/ASROB-CADE
* https://github.com/asrob-uc3m/Semana_de_Asociaciones_2017

**Comment by jgvictores** [comment]
Closing, adding `invalid` label but would be happy with an `irrelevant` label. :-)

**Comment by David-Estevez** [comment]
Let's say it is more of a `maybe later` than `invalid` :sweat_smile:
