### ISSUE TITLE
aplicar PID al sensor de linea ( Wen apréndelo)

### ISSUE THREAD

**Issue by madelgj** [asrob-uc3m/Maquiavelo#2]

**Comment by wensicm** [comment]
Wen está en ello!!!

**Comment by wensicm** [comment]
Vale, Wen confirma tras varios dias de insomnio y alucionaciones que, finalmente, el código PID esta COMPLETO en todo el sentido de la palabra. Podemos iniciar la fiesta de iniciación de Maquiavelo ;D
