### ISSUE TITLE
ICONO maquiavelo

### ISSUE THREAD

**Issue by madelgj** [asrob-uc3m/Maquiavelo#7]
Urgente necesitamos un icono de maquiavelo
también una cuenta de twitter y de instagram

**Comment by wensicm** [comment]
Aunque sigo pensando que me encanta uno de los definitivos de ayer (el que no era un gordo ceboso) he de decir que investigaré el tema.

**Comment by wensicm** [comment]
Visto que ya tenemos un logo semi-oficial, cierro issue.
